# Generated by Django 3.1.6 on 2021-02-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produuct',
            new_name='Product',
        ),
    ]
