# Generated by Django 3.1.6 on 2021-02-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('lastame', models.CharField(max_length=50)),
                ('mailid', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'web member',
            },
        ),
    ]
